language: ruby
rvm:
- 2.6
before_install:
    - gem install bundler
script: bundle exec jekyll build
addons:
  ssh_known_hosts: cwrose.de
before_deploy:
- openssl aes-256-cbc -K $encrypted_efb9211739b3_key -iv $encrypted_efb9211739b3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/_site cwrosede@cwrose.de:subdomains/serverblog/httpdocs
  on:
    branch: master
after_deploy:
- ssh-add -d
- rm /tmp/deploy_rsa
